Repository googleapis/nodejs-security-private-ca, pull requests merged in 2020-11, with the labels that each got.

#28 fix: do not modify options object, use defaultScopes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci.yaml
  .jsdoc.js
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CODE_OF_CONDUCT.md
  README.md
  linkinator.config.json
  package.json
  protos/google/cloud/security/privateca/v1beta1/resources.proto
  protos/google/cloud/security/privateca/v1beta1/service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  samples/README.md
  src/index.ts
  src/v1beta1/certificate_authority_service_client.ts
  src/v1beta1/certificate_authority_service_client_config.json
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_certificate_authority_service_v1beta1.ts
Labels: api: privateca, automerge, cla: yes, cla: yes

#21 feat!: Updates to Certificate Authority Service for Beta release
  .kokoro/trampoline_v2.sh
  README.md
  samples/quickstart.js
  src/v1beta1/certificate_authority_service_client.ts
  synth.metadata
Labels: api: privateca, cla: yes, cla: yes, do not merge

#31 build: change repo metadata for doc generation
  .repo-metadata.json
Labels: api: privateca, cla: yes, cla: yes

#26 build: stop ignoring links in linkinator.config.json
  linkinator.config.json
  protos/protos.json
  src/v1beta1/certificate_authority_service_client.ts
  synth.metadata
Labels: api: privateca, cla: yes, cla: yes, context: partial

#36 fix(browser): check for fetch on window
  src/v1beta1/certificate_authority_service_client.ts
  synth.metadata
Labels: api: privateca, cla: yes, cla: yes, context: partial
